#group群组
#list列表
#icon图标，见help-plugin/resources/icon
#title大字
#desc小字
#按你的需求修改
- group: Yunzai-Bot功能
  list:
    - icon: flower_1
      title: 'meme列表 meme帮助'
      desc: '查看可合成表情列表，如#吸'
    # - icon: wave
    #   title: '和我对话'
    #   desc: '以小罐头开头对话，只支持文字'
    - icon: switch
      title: '#联系主人'
      desc: '联系主人'
    - icon: archaic_stone
      title: '撤回'
      desc: '引用机器人发送的消息发送撤回即可撤回'
    - icon: restaurant_smoothie
      title: '开盒@某人 你几把谁啊'
      desc: '其实是看该用户的资料。必须要@某人才能用'
    - icon: spring_of_pure_sacred_dewdrop
      title: 'bilibili视频解析'
      desc: '支持小程序卡片'
    - icon: unfading_silky_grace
      title: '#水群榜'
      desc: '查看本群发言排行'
    - icon: coin
      title: '#今日运势 jrys'
      desc: '查看今天运势（娱乐）'
    # - icon: wisdom
    #   title: '#悔签'
    #   desc: '每天悔一次，悔完可以再抽一次运势'
    - icon: lumidouce_bell
      title: '#今日doro结局'
      desc: '每天一次'
    - icon: delightful_encounter
      title: '#七夕抽奖 #七夕十连'
      desc: '看看七夕表白成不成功'
    - icon: coin
      title: 'wwcos'
      desc: '查看鸣潮cos'
    - icon: 绑定账号
      title: '#扫码登录'
      desc: '绑定米游社cookie'
    - icon: 风车
      title: '#喵喵帮助'
      desc: '原神功能帮助'
    - icon: 三月七
      title: '*帮助 sr帮助'
      desc: '星铁功能帮助'
    - icon: 史莱姆
      title: '悠悠帮助'
      desc: '蓝色星原·旅谣功能帮助'

- group: Astrbot功能
  list:
    - icon: 绑定账号
      title: '/pig'
      desc: '随机猪猪图片'
    - icon: 钓鱼
      title: '🦌帮助'
      desc: '🦌签到'
    - icon: 风车
      title: '赞我'
      desc: '点10个赞'
    - icon: paimon
      title: '/裁剪 4x6'
      desc: '图片裁剪4行6列，x是字母'
    - icon: 雷神瞳共鸣石
      title: '/盒@某人'
      desc: '盒某人，与上面的盒不一样'
    # - icon: 树脂
    #   title: '#体力 #体力帮助'
    #   desc: '查询体力，绑定Cookie帮助'
    # - icon: 史莱姆
    #   title: '#日历 #日历列表'
    #   desc: '查看活动日历'
    # - icon: 星辉
    #   title: '#抽卡记录 #记录帮助'
    #   desc: '札记数据，需要绑定Cookie'
    # - icon: 原石
    #   title: '#喵喵帮助'
    #   desc: '原神帮助'
    # - icon: 纠缠之缘
    #   title: '#面板帮助'
    #   desc: '原神查询面板指引'
    # - icon: 风车
    #   title: '#深渊'
    #   desc: '打完2小时后查看'
    # - icon: paimon
    #   title: '#幻想'
    #   desc: '幻想挑战记录'
    # - icon: 派蒙
    #   title: '#幽境'
    #   desc: '幽境危战挑战数据'
    # - icon: 刻晴
    #   title: '角色面板替换'
    #   desc: '详见#面板帮助'
    # - icon: 米游社
    #   title: '#宵宫攻略'
    #   desc: '米游社的角色攻略'

- group: GsCore功能
  list:
    - icon: romaritime_flower
      title: 'core帮助'
      desc: 'GsCore帮助'
    - icon: abyss
      title: 'ww帮助'
      desc: '鸣潮功能帮助'
    - icon: role
      title: '谁at我'
      desc: '图片查看谁@我'
    # - icon: role
    #   title: '*黑塔面板'
    #   desc: '查看角色面板'
    # - icon: romaritime_flower
    #   title: '*收入'
    #   desc: '查看星琼收入，需Cookie'
    - icon: 树脂
      title: 'ww[角色]4c'
      desc: '不支持引用'
    - icon: 攻略
      title: 'ww梭哈帮助'
      desc: '抽声骸'
    # - icon: 统计
    #   title: '*忘却'
    #   desc: '忘却之庭数据'
    # - icon: 问号
    #   title: '*末日'
    #   desc: '末日幻影数据'
    - icon: pamu
      title: 'end帮助'
      desc: '终末地插件帮助'
    # - icon: 养成计算
    #   title: '*深渊'
    #   desc: '获取全部深渊数据'
    # - icon: 原石
    #   title: '*抽卡记录'
    #   desc: '抽卡记录帮助'
    # - icon: 纠缠之缘
    #   title: '*抽卡链接'
    #   desc: '绑定抽卡链接'
    # - icon: 星辉
    #   title: '*更新跃迁/抽卡'
    #   desc: '更新本地抽卡记录'
    # - icon: 记录
    #   title: '*跃迁分析[角色/光锥/常驻]'
    #   desc: '抽卡分析默认为总览'